# Generated by Django 5.2.13 on 2026-04-24 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(unique=True)),
                ('crop_name', models.CharField(blank=True, max_length=100)),
                ('area_m2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('irrigation_mode', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATIC', 'Automático'), ('SCHEDULED', 'Programado')], default='AUTOMATIC', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='farms.farm')),
            ],
            options={
                'ordering': ['farm__name', 'name'],
            },
        ),
    ]
