# Generated by Django 5.2.13 on 2026-04-24 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farm',
            options={'ordering': ['name'], 'verbose_name': 'Granja', 'verbose_name_plural': 'Granjas'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ['farm__name', 'name'], 'verbose_name': 'Zona', 'verbose_name_plural': 'Zonas'},
        ),
        migrations.AlterField(
            model_name='farm',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='location',
            field=models.CharField(max_length=150, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='area_m2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Área (m2)'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='code',
            field=models.SlugField(unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='crop_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre del cultivo'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='farms.farm', verbose_name='Granja'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='irrigation_mode',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATIC', 'Automático'), ('SCHEDULED', 'Programado')], default='AUTOMATIC', max_length=20, verbose_name='Modo de riego'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
