# Generated by Django 5.2.13 on 2026-04-24 14:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('command', models.CharField(choices=[('TURN_ON', 'Encender'), ('TURN_OFF', 'Apagar'), ('OPEN', 'Abrir'), ('CLOSE', 'Cerrar'), ('SET_AUTO', 'Modo automático'), ('SET_MANUAL', 'Modo manual')], max_length=20)),
                ('source', models.CharField(choices=[('RULE', 'Regla'), ('SCHEDULE', 'Programación'), ('MANUAL', 'Manual'), ('API', 'API')], default='MANUAL', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('SENT', 'Enviado'), ('EXECUTED', 'Ejecutado'), ('FAILED', 'Fallido'), ('CANCELED', 'Cancelado')], default='PENDING', max_length=20)),
                ('desired_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('actuator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='devices.actuator')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='irrigation_commands', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='devices.device')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='farms.zone')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(choices=[('LOW_MOISTURE', 'Humedad baja'), ('DEVICE_OFFLINE', 'Dispositivo desconectado'), ('SENSOR_ERROR', 'Error de sensor'), ('EXECUTION_FAILURE', 'Fallo de ejecución'), ('MAINTENANCE', 'Mantenimiento')], max_length=30)),
                ('severity', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='MEDIUM', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_irrigation_alerts', to=settings.AUTH_USER_MODEL)),
                ('actuator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='devices.actuator')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='devices.device')),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='devices.sensor')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='farms.zone')),
                ('command', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='automation.command')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IrrigationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('min_threshold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('action', models.CharField(choices=[('TURN_ON', 'Encender'), ('OPEN', 'Abrir')], default='TURN_ON', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(default=10)),
                ('cooldown_minutes', models.PositiveIntegerField(default=15)),
                ('active', models.BooleanField(default=True)),
                ('actuator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='devices.actuator')),
                ('sensor', models.ForeignKey(limit_choices_to={'sensor_type': 'SOIL_MOISTURE'}, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='devices.sensor')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='farms.zone')),
            ],
            options={
                'ordering': ['zone__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='command',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commands', to='automation.irrigationrule'),
        ),
        migrations.CreateModel(
            name='IrrigationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('days_of_week', models.CharField(help_text='Ejemplo: MON,TUE,WED', max_length=50)),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=10)),
                ('active', models.BooleanField(default=True)),
                ('actuator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='devices.actuator')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='farms.zone')),
            ],
            options={
                'ordering': ['zone__name', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='command',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commands', to='automation.irrigationschedule'),
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quality', models.CharField(choices=[('GOOD', 'Buena'), ('ESTIMATED', 'Estimada'), ('BAD', 'Mala')], default='GOOD', max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='devices.sensor')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
