# Generated by Django 5.2.13 on 2026-04-24 14:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
        ('devices', '0002_alter_actuator_options_alter_device_options_and_more'),
        ('farms', '0002_alter_farm_options_alter_zone_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-created_at'], 'verbose_name': 'Alerta', 'verbose_name_plural': 'Alertas'},
        ),
        migrations.AlterModelOptions(
            name='command',
            options={'ordering': ['-created_at'], 'verbose_name': 'Comando', 'verbose_name_plural': 'Comandos'},
        ),
        migrations.AlterModelOptions(
            name='irrigationrule',
            options={'ordering': ['zone__name', 'name'], 'verbose_name': 'Regla de riego', 'verbose_name_plural': 'Reglas de riego'},
        ),
        migrations.AlterModelOptions(
            name='irrigationschedule',
            options={'ordering': ['zone__name', 'start_time'], 'verbose_name': 'Programación de riego', 'verbose_name_plural': 'Programaciones de riego'},
        ),
        migrations.AlterModelOptions(
            name='sensorreading',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Lectura de sensor', 'verbose_name_plural': 'Lecturas de sensores'},
        ),
        migrations.AlterField(
            model_name='alert',
            name='acknowledged',
            field=models.BooleanField(default=False, verbose_name='Reconocida'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reconocida el'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_irrigation_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Reconocida por'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='actuator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='devices.actuator', verbose_name='Actuador'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('LOW_MOISTURE', 'Humedad baja'), ('DEVICE_OFFLINE', 'Dispositivo desconectado'), ('SENSOR_ERROR', 'Error de sensor'), ('EXECUTION_FAILURE', 'Fallo de ejecución'), ('MAINTENANCE', 'Mantenimiento')], max_length=30, verbose_name='Tipo de alerta'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='command',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='automation.command', verbose_name='Comando'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='devices.device', verbose_name='Dispositivo'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='message',
            field=models.TextField(verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='devices.sensor', verbose_name='Sensor'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='MEDIUM', max_length=20, verbose_name='Severidad'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='farms.zone', verbose_name='Zona'),
        ),
        migrations.AlterField(
            model_name='command',
            name='actuator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='devices.actuator', verbose_name='Actuador'),
        ),
        migrations.AlterField(
            model_name='command',
            name='command',
            field=models.CharField(choices=[('TURN_ON', 'Encender'), ('TURN_OFF', 'Apagar'), ('OPEN', 'Abrir'), ('CLOSE', 'Cerrar'), ('SET_AUTO', 'Modo automático'), ('SET_MANUAL', 'Modo manual')], max_length=20, verbose_name='Comando'),
        ),
        migrations.AlterField(
            model_name='command',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='irrigation_commands', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='command',
            name='desired_duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duración deseada (minutos)'),
        ),
        migrations.AlterField(
            model_name='command',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='devices.device', verbose_name='Dispositivo'),
        ),
        migrations.AlterField(
            model_name='command',
            name='executed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ejecutado el'),
        ),
        migrations.AlterField(
            model_name='command',
            name='payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Payload'),
        ),
        migrations.AlterField(
            model_name='command',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commands', to='automation.irrigationrule', verbose_name='Regla'),
        ),
        migrations.AlterField(
            model_name='command',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commands', to='automation.irrigationschedule', verbose_name='Programación'),
        ),
        migrations.AlterField(
            model_name='command',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Enviado el'),
        ),
        migrations.AlterField(
            model_name='command',
            name='source',
            field=models.CharField(choices=[('RULE', 'Regla'), ('SCHEDULE', 'Programación'), ('MANUAL', 'Manual'), ('API', 'API')], default='MANUAL', max_length=20, verbose_name='Origen'),
        ),
        migrations.AlterField(
            model_name='command',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('SENT', 'Enviado'), ('EXECUTED', 'Ejecutado'), ('FAILED', 'Fallido'), ('CANCELED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='command',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='farms.zone', verbose_name='Zona'),
        ),
        migrations.AlterField(
            model_name='irrigationrule',
            name='action',
            field=models.CharField(choices=[('TURN_ON', 'Encender'), ('OPEN', 'Abrir')], default='TURN_ON', max_length=20, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='irrigationrule',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='irrigationrule',
            name='actuator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='devices.actuator', verbose_name='Actuador'),
        ),
        migrations.AlterField(
            model_name='irrigationrule',
            name='cooldown_minutes',
            field=models.PositiveIntegerField(default=15, verbose_name='Tiempo de espera (minutos)'),
        ),
        migrations.AlterField(
            model_name='irrigationrule',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=10, verbose_name='Duración (minutos)'),
        ),
        migrations.AlterField(
            model_name='irrigationrule',
            name='min_threshold',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Umbral mínimo'),
        ),
        migrations.AlterField(
            model_name='irrigationrule',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='irrigationrule',
            name='sensor',
            field=models.ForeignKey(limit_choices_to={'sensor_type': 'SOIL_MOISTURE'}, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='devices.sensor', verbose_name='Sensor'),
        ),
        migrations.AlterField(
            model_name='irrigationrule',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='farms.zone', verbose_name='Zona'),
        ),
        migrations.AlterField(
            model_name='irrigationschedule',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='irrigationschedule',
            name='actuator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='devices.actuator', verbose_name='Actuador'),
        ),
        migrations.AlterField(
            model_name='irrigationschedule',
            name='days_of_week',
            field=models.CharField(help_text='Ejemplo: MON,TUE,WED', max_length=50, verbose_name='Días de la semana'),
        ),
        migrations.AlterField(
            model_name='irrigationschedule',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=10, verbose_name='Duración (minutos)'),
        ),
        migrations.AlterField(
            model_name='irrigationschedule',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='irrigationschedule',
            name='start_time',
            field=models.TimeField(verbose_name='Hora de inicio'),
        ),
        migrations.AlterField(
            model_name='irrigationschedule',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='farms.zone', verbose_name='Zona'),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='quality',
            field=models.CharField(choices=[('GOOD', 'Buena'), ('ESTIMATED', 'Estimada'), ('BAD', 'Mala')], default='GOOD', max_length=20, verbose_name='Calidad'),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='raw_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Payload crudo'),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='devices.sensor', verbose_name='Sensor'),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora'),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor'),
        ),
        migrations.CreateModel(
            name='IrrigationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Hora de inicio')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de fin')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duración real (minutos)')),
                ('water_volume_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Volumen de agua (litros)')),
                ('actuator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='devices.actuator', verbose_name='Actuador')),
                ('command', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='automation.command', verbose_name='Comando')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='farms.zone', verbose_name='Zona')),
            ],
            options={
                'verbose_name': 'Historial de riego',
                'verbose_name_plural': 'Historial de riego',
                'ordering': ['-start_time'],
            },
        ),
    ]
