# Generated by Django 5.2.13 on 2026-04-24 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('CONTROLLER', 'Controlador'), ('GATEWAY', 'Gateway')], default='CONTROLLER', max_length=20)),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('MAINTENANCE', 'Mantenimiento')], default='OFFLINE', max_length=20)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='farms.zone')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Actuator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('actuator_type', models.CharField(choices=[('PUMP', 'Bomba'), ('VALVE', 'Válvula'), ('RELAY', 'Relé')], max_length=20)),
                ('pin', models.CharField(blank=True, max_length=20)),
                ('state', models.CharField(choices=[('OFF', 'Apagado'), ('ON', 'Encendido'), ('OPEN', 'Abierto'), ('CLOSED', 'Cerrado')], default='OFF', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actuators', to='farms.zone')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actuators', to='devices.device')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('sensor_type', models.CharField(choices=[('SOIL_MOISTURE', 'Humedad de suelo'), ('TEMPERATURE', 'Temperatura'), ('HUMIDITY', 'Humedad ambiental'), ('FLOW', 'Caudal'), ('PRESSURE', 'Presión'), ('RAIN', 'Lluvia')], max_length=30)),
                ('unit', models.CharField(max_length=20)),
                ('pin', models.CharField(blank=True, max_length=20)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('active', models.BooleanField(default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='devices.device')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='farms.zone')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
