# Generated by Django 5.2.13 on 2026-04-24 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('farms', '0002_alter_farm_options_alter_zone_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actuator',
            options={'ordering': ['name'], 'verbose_name': 'Actuador', 'verbose_name_plural': 'Actuadores'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['name'], 'verbose_name': 'Dispositivo', 'verbose_name_plural': 'Dispositivos'},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'ordering': ['name'], 'verbose_name': 'Sensor', 'verbose_name_plural': 'Sensores'},
        ),
        migrations.AlterField(
            model_name='actuator',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='actuator',
            name='actuator_type',
            field=models.CharField(choices=[('PUMP', 'Bomba'), ('VALVE', 'Válvula'), ('RELAY', 'Relé')], max_length=20, verbose_name='Tipo de actuador'),
        ),
        migrations.AlterField(
            model_name='actuator',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actuators', to='devices.device', verbose_name='Dispositivo'),
        ),
        migrations.AlterField(
            model_name='actuator',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='actuator',
            name='pin',
            field=models.CharField(blank=True, max_length=20, verbose_name='Pin'),
        ),
        migrations.AlterField(
            model_name='actuator',
            name='state',
            field=models.CharField(choices=[('OFF', 'Apagado'), ('ON', 'Encendido'), ('OPEN', 'Abierto'), ('CLOSED', 'Cerrado')], default='OFF', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='actuator',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actuators', to='farms.zone', verbose_name='Zona'),
        ),
        migrations.AlterField(
            model_name='device',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='ID del Dispositivo'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('CONTROLLER', 'Controlador'), ('GATEWAY', 'Gateway')], default='CONTROLLER', max_length=20, verbose_name='Tipo de dispositivo'),
        ),
        migrations.AlterField(
            model_name='device',
            name='firmware_version',
            field=models.CharField(blank=True, max_length=50, verbose_name='Versión de firmware'),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP'),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última vez visto'),
        ),
        migrations.AlterField(
            model_name='device',
            name='mac_address',
            field=models.CharField(blank=True, max_length=50, verbose_name='Dirección MAC'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('ONLINE', 'En línea'), ('OFFLINE', 'Desconectado'), ('MAINTENANCE', 'Mantenimiento')], default='OFFLINE', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='device',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='farms.zone', verbose_name='Zona'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='devices.device', verbose_name='Dispositivo'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='max_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor máximo'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='min_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor mínimo'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='pin',
            field=models.CharField(blank=True, max_length=20, verbose_name='Pin'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(choices=[('SOIL_MOISTURE', 'Humedad de suelo'), ('TEMPERATURE', 'Temperatura'), ('HUMIDITY', 'Humedad ambiental'), ('FLOW', 'Caudal'), ('PRESSURE', 'Presión'), ('RAIN', 'Lluvia')], max_length=30, verbose_name='Tipo de sensor'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='unit',
            field=models.CharField(max_length=20, verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='farms.zone', verbose_name='Zona'),
        ),
    ]
